package application.data.mapping;
// Generated 09/05/2018 23:15:18 by Hibernate Tools 4.3.1



/**
 * Perfilusuario generated by hbm2java
 */
public class Perfilusuario  implements java.io.Serializable {


     private int id;
     private Perfil perfil;
     private Usuarios usuarios;

    public Perfilusuario() {
    }

    public Perfilusuario(int id, Perfil perfil, Usuarios usuarios) {
       this.id = id;
       this.perfil = perfil;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }




}


