package application.data.mapping;
// Generated 09/05/2018 23:15:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private String nome;
     private String login;
     private String senha;
     private Set perfilusuarios = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Usuarios(int id, String nome, String login, String senha, Set perfilusuarios) {
       this.id = id;
       this.nome = nome;
       this.login = login;
       this.senha = senha;
       this.perfilusuarios = perfilusuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getPerfilusuarios() {
        return this.perfilusuarios;
    }
    
    public void setPerfilusuarios(Set perfilusuarios) {
        this.perfilusuarios = perfilusuarios;
    }




}


